### PR TITLE
Resolve #32

### LINKED ISSUE #32: Base image used by APPS PLAID is not supported
## Vulnerability

"APPS PLAID" uses as its base Docker image `php:5.6-apache-jessie`.

Debian Linux `jessie` reached end-of-life on 2018-06-17 and end of long-term support on 2020-06-30. It has received no security updates since then.

PHP 5.6 reached end of life on 2019-01-01 and has no long-term support. It has received no security updates since then.

Upgrading the base image of "APPS PLAID" is strenuously recommended.

## Software Version
`main`

### PR DESCRIPTION
**Pull request by nutjob4life**
## 🗒️ Summary

Merge this—if you dare—to resolve #32. This upgrades PHP from 5.6 to 7.4.27 which, as of this writing, is considered safe. Note that 8.1 is out, however there were an even higher number of issues trying to jump all the way to it.

## ⚙️ Test Data and/or Report
```console
$ cd /tmp
$ python3 -m venv venv
$ cd venv
$ bin/pip install --quiet --upgrade setuptools pip
$ bin/pip install --quiet selenium webdriver_manager
$ curl --silent --location https://raw.githubusercontent.com/NASA-PDS/PLAID/main/tests/create_context_label_test.py | sed -e 's/Eyasu.T.Haile@jpl.nasa.gov/kelly@jpl.nasa.gov/' -e 's/pass/x/' > run.py
$ bin/python run.py
…
$ echo \U+1F389
🎉
```

## ♻️ Related Issues

- #32

### CODE REVIEW

**Comment by jordanpadams** [comment]
@voxparcxls can you please test and review these changes?

**Comment by voxparcxls** [comment]
@jordanpadams  
@nutjob4life

#### PR looks good!

**1. New PHP 7.4.27 worked great.**
      * PLAID image was generate and run by Docker set to local machine ENV 
      * Started up with `docker-compose up`

**2. Selenium test ran successfully.** 

Screen Shot 2022-01-27 at 11 56 53 AM
 
* Test values were used to generate the 'ContextLabel Test 1'. 


**3. Selenium create, populated, and previewed the label successfully.**

Screen Shot 2022-01-27 at 11 54 04 AM


:clap: :smile:

**Comment by nutjob4life** [comment]
WOOOT! 🎉 Thanks @voxparcxls! 👏

**Comment by jordanpadams** [comment]
this was almost like a fun open source community fix and merge! we did it! 🎉

**Comment by stirlingalgermissen** [comment]
👏🎉

**Pull request merged**
